<a href="https://www.kaggle.com/code/mohdmuttalib/eda-novozymes-enzyme-stability-prediction?scriptVersionId=109544653" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## Contact Information

- **Name** - Mohd Muttalib
- **Phone** - +91-8445818187
- **Email** - muttalib1326@gmail.com
- **Portfolio** -[link](https://www.kaggle.com/mohdmuttalib)

<center><img src="https://storage.googleapis.com/kaggle-competitions/kaggle/37190/logos/header.png?t=2022-08-30-15-34-26" width=1000></center>



<div class="alert alert-block alert-info">
<center><h1>Novozymes Enzyme Stability Prediction</h1></center>
<center><h3>Help identify the thermostable mutations in enzymes</h3></center>
</div>
<div class="alert alert-block alert-success">
<center><h1>EDA + XGBoost</h1></center>
</div>


### <h1>Table of contents</h1><a class='anchor' id='top'></a>
- [Import libraries](#import)
- [Utils](#utils)
- [Config](#config)
- [Load data](#load)
- [Train profiling](#train_profiling)
- [Test profiling](#test_profiling)
- [What is PDB?](#pdb)
- [Label Encode](#labelencode)
- [XGBoost Regressor](#xgboost)
- [Evaluate: Spearman's rank correlation coefficient](#evaluate)
- [Predict](#predict)
- [Submission](#submission)


<div class="alert alert-block alert-warning">  
<b>Note:</b> This is a work in progress ⚠️
</div>

<div class="alert alert-block alert-info">
<center><h1>What is the goal of this competition?</h1></center>
</div>

<div class="alert alert-block alert-info">
The goal of this competition is to predict the thermal stability of enzyme variants. The experimentally measured thermal stability (melting temperature) data includes natural sequences, as well as engineered sequences with single or multiple mutations upon the natural sequences.

A point mutation is a genetic mutation where a single nucleotide base is changed, inserted or deleted from a DNA or RNA sequence of an organism's genome. Point mutations have a variety of effects on the downstream protein product—consequences that are moderately predictable based upon the specifics of the mutation.

These consequences can range from no effect (e.g. synonymous mutations) to deleterious effects (e.g. frameshift mutations), with regard to protein production, composition, and function.
</div>




<div class="alert alert-block alert-success">
<center><h1>What is an enzyme?</h1></center>
</div>
<div class="alert alert-block alert-success">
Enzymes are proteins that act as biological catalysts by accelerating chemical reactions. An enzyme is therefore a molecule that increases the speed of biochemical reaction in an organism. The molecules upon which enzymes may act are called substrates, and the enzyme converts the substrates into different molecules known as products.
</div>
<center><img src="https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F3197853%2F011e8e6d88265aaf8d13c7b9cae4b2b8%2Fenzyme_substrate.jpeg?generation=1663958942493732&alt=media" width=800></center>
<div class="alert alert-block alert-success">
<center><h1>What is a protein?</h1></center>
</div>
<div class="alert alert-block alert-success">
Proteins are large biomolecules and macromolecules that comprise one or more long chains of amino acid residues. Proteins are also known as polypeptides.

Peptides are short chains of amino acids linked by peptide bonds. Chains of fewer than twenty amino acids are called oligopeptides, and include dipeptides, tripeptides, and tetrapeptides. So, a polypeptide is a longer, continuous, unbranched peptide chain.
</div>
<center><img src="https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F3197853%2F649adf375f36aaf3cad5064cf8d543eb%2Fprotein_structure.jpeg?generation=1663958961249770&alt=media" width=600></center>
<div class="alert alert-block alert-success">
<center><h1>What is an amino acid?</h1></center>
</div>
<div class="alert alert-block alert-success">
Amino acids are organic compounds that contain both amino and carboxylic acid functional groups. Although hundreds of amino acids exist in nature, by far the most prevalent are the alpha-amino acids, which comprise proteins.
</div>
<center><img src="https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F3197853%2Ff6f63060a29aa51e3675e36e27c51b9d%2Faminoacids.png?generation=1663958987152864&alt=media" width=600></center>



In [1]:
!pip install biopandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 879.0/879.0 kB 7.1 MB/s eta 0:00:00


# Import libraries <a class='anchor' id='import'></a> [↑](#top)

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import pandas_profiling
import time
import torch
import torch.nn as nn

# Utils <a class='anchor' id='utils'></a>[↑](#top)

In [3]:
def sep():
    print("-"*100)

# Config <a class='anchor' id='config'></a>[↑](#top)

In [4]:
class paths:
    TRAIN = "/kaggle/input/novozymes-enzyme-stability-prediction/train.csv"
    TEST = "/kaggle/input/novozymes-enzyme-stability-prediction/test.csv"
    SUBMISSION = "/kaggle/input/novozymes-enzyme-stability-prediction/sample_submission.csv"
    PDB_FILE = "/kaggle/input/novozymes-enzyme-stability-prediction/wildtype_structure_prediction_af2.pdb"

# Load data <a class='anchor' id='load'></a>[↑](#top)

Let's load the competition's data.

In [5]:
train_df = pd.read_csv(paths.TRAIN)
test_df = pd.read_csv(paths.TEST)
print(f"Train dataframe has shape: {train_df.shape}")
print(f"Test dataframe has shape: {test_df.shape}")
display(train_df.head())
display(test_df.head())

Train dataframe has shape: (31390, 5)
Test dataframe has shape: (2413, 4)


seq_id                                   protein_sequence   pH  \
0       0  AAAAKAAALALLGEAPEVVDIWLPAGWRQPFRVFRLERKGDGVLVG...  7.0   
1       1  AAADGEPLHNEEERAGAGQVGRSLPQESEEQRTGSRPRRRRDLGSR...  7.0   
2       2  AAAFSTPRATSYRILSSAGSGSTRADAPQVRRLHTTRDLLAKDYYA...  7.0   
3       3  AAASGLRTAIPAQPLRHLLQPAPRPCLRPFGLLSVRAGSARRSGLL...  7.0   
4       4  AAATKSGPRRQSQGASVRTFTPFYFLVEPVDTLSVRGSSVILNCSA...  7.0   

                         data_source    tm  
0  doi.org/10.1038/s41592-020-0801-4  75.7  
1  doi.org/10.1038/s41592-020-0801-4  50.5  
2  doi.org/10.1038/s41592-020-0801-4  40.5  
3  doi.org/10.1038/s41592-020-0801-4  47.2  
4  doi.org/10.1038/s41592-020-0801-4  49.5

seq_id                                   protein_sequence  pH data_source
0   31390  VPVNPEPDATSVENVAEKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   Novozymes
1   31391  VPVNPEPDATSVENVAKKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   Novozymes
2   31392  VPVNPEPDATSVENVAKTGSGDSQSDPIKADLEVKGQSALPFDVDC...   8   Novozymes
3   31393  VPVNPEPDATSVENVALCTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   Novozymes
4   31394  VPVNPEPDATSVENVALFTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   Novozymes

# Train profiling <a class='anchor' id='train_profiling'></a>[↑](#top)

- `protein_sequence`: has a high cardinality: 28981 distinct values ---> High cardinality
- `data_source`: has a high cardinality: 324 distinct values ---> High cardinality
- `data_source` has 3347 (10.7%) missing values ---> Missing
- `protein_sequence_len` is highly skewed (γ1 = 29.89928625) ---> Skewed
- `seq_id` is uniformly distributed ---> Uniform
- `protein_sequence` is uniformly distributed ---> Uniform
- `seq_id` has unique values

In [6]:
train_df.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Test profiling <a class='anchor' id='test_profiling'></a>[↑](#top)

- `pH` has constant value "8" ---> Constant
- `data_source` has constant value "Novozymes" ---> Constant
- `protein_sequence` has a high cardinality: 2413 distinct values ---> High cardinality
- `pH` is highly correlated with data_source and 1 other fields ---> High correlation
- `data_source` is highly correlated with pH and 1 other fields ---> High correlation
- `protein_sequence_len` is highly correlated with pH and 1 other fields ---> High correlation
- `seq_id` is uniformly distributed ---> Uniform
- `protein_sequence` is uniformly distributed ---> Uniform
- `seq_id` has unique values ---> Unique
- `protein_sequence` has unique values

In [7]:
test_df.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

### Plot target [↑](#top)

Let's plot our target so we can get a sense of its distribution. We can see that it's right skewed with a large value around 25.

In [8]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go


fig = go.Figure()
colors = ["#00FFFB", "#002EFF"]

i = 0
# Add one subplot
fig.add_trace(
    go.Histogram(x=train_df["tm"],
               name="tm",
               hovertemplate = "target column" + ' %{y:.2f}',
               marker=dict(color=colors[i])
              )
)
fig.update_xaxes(
    title_text="Target column",
    title_font_color=colors[i],
    tickfont_color=colors[i]) 
fig.update_yaxes(
    title_text = "Frequency", 
    title_font_color=colors[i], 
    tickfont_color=colors[i]) 
    
fig.update_layout(height=800,
                  width=1000,
                  title_text="Target column: Higher tm means the protein variant is more stable.",
                  template="plotly_dark",
                  xaxis=dict(color="#FF9300"),
                  yaxis=dict(color="#FF9300"))

fig.update_traces(marker_line_width=0.1,marker_line_color=colors[1])
fig.show()

### Sequence length [↑](#top)

Sequence length seems to vary for the `train.csv` while it is constant for `test.csv`

We can see there is one heavy outlier of length `32767`. The distribution is highly right skewed.

In [9]:
train_df["protein_sequence_len"] = train_df["protein_sequence"].apply(lambda x: len(x))
test_df["protein_sequence_len"] = test_df["protein_sequence"].apply(lambda x: len(x))
print("----------- TRAIN -----------")
display(train_df[["protein_sequence_len"]].describe())
print("----------- TEST -----------")
display(test_df[["protein_sequence_len"]].describe())

----------- TRAIN -----------


protein_sequence_len
count          31390.000000
mean             447.669513
std              640.728935
min                5.000000
25%              197.000000
50%              336.000000
75%              523.000000
max            32767.000000

----------- TEST -----------


protein_sequence_len
count           2413.000000
mean             220.968090
std                0.175798
min              220.000000
25%              221.000000
50%              221.000000
75%              221.000000
max              221.000000

In [10]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go


fig = go.Figure()
colors = ["#FF00F0", "#BD00FF"]

i = 0
# Add one subplot
fig.add_trace(
    go.Histogram(x=train_df["protein_sequence_len"],
               name="protein_sequence_len",
               hovertemplate = 'Protein Sequence Length:  %{x:.2f}' + '<br>Frequency: %{y:.2f}</br>',
               marker=dict(color=colors[i])
              )
)
fig.update_xaxes(
    title_text="Protein Sequence Length",
    title_font_color=colors[i],
    tickfont_color=colors[i],
    range=[0, 1500]
) 
fig.update_yaxes(
    title_text = "Frequency", 
    title_font_color=colors[i], 
    tickfont_color=colors[i]
) 

fig.update_layout(height=800,
                  width=1000,
                  title_text="Potein Sequence Length Histogram.",
                  template="plotly_dark",
                  xaxis=dict(color="#FF9300"),
                  yaxis=dict(color="#FF9300"))
fig.update_traces(marker_line_width=2,marker_line_color=colors[1])

fig.show()

# What is PDB? <a class='anchor' id='pdb'></a>[↑](#top)

PDB file format

In the PDB data file format for macromolecular models, each atom is designated either ATOM or HETATM (which stands for hetero atom).

ATOM is reserved for atoms in standard residues of protein, DNA or RNA.

HETATM is applied to non-standard residues of protein, DNA or RNA, as well as atoms in other kinds of groups, such as carbohydrates, substrates, ligands, solvent, and metal ions.

In [11]:
from biopandas.pdb import PandasPdb

pdb_df =  PandasPdb().read_pdb(paths.PDB_FILE)
pdb_df.df.keys()

dict_keys(['ATOM', 'HETATM', 'ANISOU', 'OTHERS'])

### Get dataframes

The `pdb` file contains data which we can convert into new dataframes. Let's check it out.

In [12]:
atom_df = pdb_df.df['ATOM']
hetatm_df = pdb_df.df['HETATM']
anisou_df = pdb_df.df['ANISOU']
others_df = pdb_df.df['OTHERS']
print(f"ATOM dataset is of shape: {atom_df.shape}"), sep()
print(f"HETATM dataset is of shape: {hetatm_df.shape}"), sep()
print(f"ANISOU dataset is of shape: {anisou_df.shape}"), sep()
print(f"OTHERS dataset is of shape: {others_df.shape}"), sep()
display(atom_df.head())
display(hetatm_df.head())
display(anisou_df.head())
display(others_df.head())

ATOM dataset is of shape: (3317, 21)
----------------------------------------------------------------------------------------------------
HETATM dataset is of shape: (0, 21)
----------------------------------------------------------------------------------------------------
ANISOU dataset is of shape: (0, 21)
----------------------------------------------------------------------------------------------------
OTHERS dataset is of shape: (2, 3)
----------------------------------------------------------------------------------------------------


record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
0        ATOM            1                 N                  VAL           
1        ATOM            2                 H                  VAL           
2        ATOM            3                H2                  VAL           
3        ATOM            4                H3                  VAL           
4        ATOM            5                CA                  VAL           

  chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
0        A               1            ...  34.064   -6.456   50.464   
1        A               1            ...  33.576   -6.009   51.228   
2        A               1            ...  33.882   -7.449   50.477   
3        A               1            ...  35.060   -6.323   50.566   
4        A               1            ...  33.643   -5.877   49.162   

   occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
0        1.0     45.11                                  N    NaN         0  
1        1.0     45.11                                  H    NaN         1  
2        1.0     45.11                                  H    NaN         2  
3        1.0     45.11                                  H    NaN         3  
4        1.0     45.11                                  C    NaN         4  

[5 rows x 21 columns]

Empty DataFrame
Columns: [record_name, atom_number, blank_1, atom_name, alt_loc, residue_name, blank_2, chain_id, residue_number, insertion, blank_3, x_coord, y_coord, z_coord, occupancy, b_factor, blank_4, segment_id, element_symbol, charge, line_idx]
Index: []

[0 rows x 21 columns]

Empty DataFrame
Columns: [record_name, atom_number, blank_1, atom_name, alt_loc, residue_name, blank_2, chain_id, residue_number, insertion, blank_3, U(1,1), U(2,2), U(3,3), U(1,2), U(1,3), U(2,3), blank_4, element_symbol, charge, line_idx]
Index: []

[0 rows x 21 columns]

record_name                 entry  line_idx
0         TER   3318      LYS A 221      3317
1         END                            3318

### Plot sequence

In [13]:
import plotly.express as px

fig = px.scatter_3d(atom_df, x = "x_coord",
                    y = "y_coord",
                    z = "z_coord",
                    color = "element_symbol",
                    color_discrete_sequence = ["#84FFA9", "#00FFF7", "#003AFF", "#F000FF", "#FBFF00"])
fig.update_traces(marker = dict(size = 3))
fig.update_coloraxes(showscale = False)
fig.update_layout(template = "plotly_dark")
fig.show()

### Get sequences [↑](#top)

We will only use sequences lower than 221.

In [14]:
from scipy.sparse import csr_matrix

train_df = train_df[train_df["protein_sequence_len"]<=221]
train_df.reset_index(inplace=True)
sequences = [list(string) for string in train_df["protein_sequence"].values.tolist()]
sequences_train = pd.DataFrame(sequences)
sequences_train.head()

0   1   2   3   4   5   6   7   8   9    ...   211   212   213   214   215  \
0   A   A   F   Q   V   T   S   N   E   I  ...  None  None  None  None  None   
1   A   A   G   G   Q   P   Q   G   A   T  ...     A     Q     Q     Q     C   
2   A   A   I   G   I   G   I   L   G   G  ...  None  None  None  None  None   
3   A   A   K   S   G   D   A   E   E   A  ...  None  None  None  None  None   
4   A   A   L   A   L   G   L   P   A   F  ...  None  None  None  None  None   

    216   217   218   219   220  
0  None  None  None  None  None  
1     N  None  None  None  None  
2  None  None  None  None  None  
3  None  None  None  None  None  
4  None  None  None  None  None  

[5 rows x 221 columns]

# Label encode <a class='anchor' id='labelencode'></a>[↑](#top)

We need to label encode data so we can use XGBoost Regressor

In [15]:
from sklearn.preprocessing import LabelEncoder

sequences_train = sequences_train.apply(LabelEncoder().fit_transform)
sequences_train["tm"] = train_df["tm"]
sequences_train.head()

0  1  2   3   4   5   6   7  8   9  ...  212  213  214  215  216  217  218  \
0  0  0  4  13  17  16  15  11  3   7  ...   20   19   20   20   20   20   20   
1  0  0  5   5  13  12  13   5  0  16  ...   13   13   13    1   11   20   20   
2  0  0  7   5   7   5   7   9  5   5  ...   20   19   20   20   20   20   20   
3  0  0  8  15   5   2   0   3  3   0  ...   20   19   20   20   20   20   20   
4  0  0  9   0   9   5   9  12  0   4  ...   20   19   20   20   20   20   20   

   219  220    tm  
0   20   18  49.7  
1   20   18  45.1  
2   20   18  62.8  
3   20   18  36.3  
4   20   18  83.0  

[5 rows x 222 columns]

# XGBoost Regressor <a class='anchor' id='xgboost'></a>[↑](#top)

Let's make a 80/20 split and train a XGBoost regressor.

In [16]:
from sklearn.model_selection import train_test_split
import xgboost

X = sequences_train.loc[:, sequences_train.columns != "tm"]
y = sequences_train.loc[:, sequences_train.columns == "tm"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# create an xgboost regression model
model = xgboost.XGBRegressor(n_estimators=500, max_depth=15)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate: Spearman's rank correlation coefficient <a class='anchor' id='evaluate'></a>[↑](#top)

We need to evaluate with [Spearman's rank correlation coefficient](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient)

In [17]:
from scipy import stats

stats.spearmanr(y_test, y_pred)

SpearmanrResult(correlation=0.3547764232104556, pvalue=9.909469529327458e-55)

# Predict <a class='anchor' id='predict'></a>[↑](#top)

Now that the model is trained let's convert the `test` dataframe into the required format and get predictions.

In [18]:
from scipy.sparse import csr_matrix

test_df = test_df[test_df["protein_sequence_len"]<=221]
sequences = [list(string) for string in test_df["protein_sequence"].values.tolist()]
sequences_test = pd.DataFrame(sequences)
sequences_test = sequences_test.apply(LabelEncoder().fit_transform)
sequences_test.head()

0    1    2    3    4    5    6    7    8    9    ...  211  212  213  214  \
0    0    0    0    0    0    0    0    0    0    0  ...    7   11    7    5   
1    0    0    0    0    0    0    0    0    0    0  ...    7   11    7    5   
2    0    0    0    0    0    0    0    0    0    0  ...   10   11    6    2   
3    0    0    0    0    0    0    0    0    0    0  ...    7   11    7    5   
4    0    0    0    0    0    0    0    0    0    0  ...    7   11    7    5   

   215  216  217  218  219  220  
0    1    8   13   15    2    6  
1    1    8   13   15    2    6  
2    5   16   11    4    4   13  
3    1    8   13   15    2    6  
4    1    8   13   15    2    6  

[5 rows x 221 columns]

# Submission <a class='anchor' id='submission'></a>[↑](#top)

Finally, let's submit our predictions.

In [19]:
submission = pd.DataFrame()
submission["tm"] = model.predict(sequences_test)
submission["seq_id"] = test_df["seq_id"]
submission.to_csv("submission.csv", index=False)